// SPDX-License-Identifier: Apache-2.0
//
// QA scenarios (Phase 9): JSON files in <project>/.modulex/tests/*.json, authored by the QA role from the GDD, or
// generated by `defaultScenarios` for every game. Steps map one-to-one onto the in-game QA tools; assertions are
// evaluated by the runner on `game-state-get` / `game-node-find` / `game-ui-inspect` results.
import { z } from 'zod';
import type { GameSpec } from '@modulex/shared';
import type { GeneratedProject } from '../project/game-generator.js';

const Assertion = z.discriminatedUnion('kind', [
  z
    .object({
      kind: z.literal('state'),
      field: z.enum(['currentScene', 'paused', 'playerFound', 'playerY', 'frame', 'nodeCount']),
      op: z.enum(['eq', 'gt', 'lt', 'ne']),
      value: z.union([z.string(), z.number(), z.boolean()]),
    })
    .strict(),
  z.object({ kind: z.literal('player_moved'), min: z.number().positive() }).strict(),
  z
    .object({
      kind: z.literal('node'),
      group: z.string().optional(),
      type: z.string().optional(),
      path: z.string().optional(),
      min: z.number().int().nonnegative(),
    })
    .strict(),
  z.object({ kind: z.literal('ui_ok') }).strict(),
]);
export type Assertion = z.infer<typeof Assertion>;

const Step = z.discriminatedUnion('op', [
  z
    .object({
      op: z.literal('wait'),
      frames: z.number().int().positive().optional(),
      seconds: z.number().positive().optional(),
      untilSignal: z.string().optional(),
      untilNodePath: z.string().optional(),
      pressAction: z.string().optional(),
    })
    .strict(),
  z.object({ op: z.literal('input'), action: z.string(), frames: z.number().int().positive().default(10) }).strict(),
  z.object({ op: z.literal('mark') }).strict(),
  z.object({ op: z.literal('assert'), assert: Assertion }).strict(),
  z.object({ op: z.literal('screenshot'), check: z.enum(['not_blank', 'none']).default('not_blank') }).strict(),
  z.object({ op: z.literal('scene-change'), scene: z.string().regex(/^res:\/\//) }).strict(),
  /** Poll game-state-get until `assert` holds or the timeout expires (e.g. "boots within N s"). */
  z.object({ op: z.literal('await'), assert: Assertion, timeout_s: z.number().positive().max(120) }).strict(),
]);
export type Step = z.infer<typeof Step>;

export const ScenarioSchema = z
  .object({
    id: z.string().regex(/^[a-z0-9][a-z0-9_-]*$/),
    title: z.string().min(1),
    /** Why this scenario exists (GDD reference or default rule). */
    covers: z.string().min(1),
    steps: z.array(Step).min(1),
  })
  .strict();
export type Scenario = z.infer<typeof ScenarioSchema>;

/** The default scenarios for a generated game (Phase 9 list), each tied to the rule it covers. */
export function defaultScenarios(spec: GameSpec, g: GeneratedProject): Scenario[] {
  const level1 = g.levelScenes[0]!;
  const level2 = g.levelScenes[1];
  const inLevel: Step[] = [
    { op: 'scene-change', scene: level1 },
    { op: 'await', assert: { kind: 'state', field: 'playerFound', op: 'eq', value: true }, timeout_s: 10 },
    { op: 'wait', frames: 30 },
  ];
  const s: Scenario[] = [
    {
      id: 'boot',
      title: 'Boots to the main scene',
      covers: 'default: boots to the main scene within 15 s',
      steps: [
        { op: 'await', assert: { kind: 'state', field: 'currentScene', op: 'eq', value: g.mainScene }, timeout_s: 15 },
      ],
    },
    {
      id: 'player-moves',
      title: 'The player moves when move_forward is held',
      covers: 'default: the player exists and moves on move_* input',
      steps: [
        ...inLevel,
        { op: 'mark' },
        { op: 'input', action: 'move_forward', frames: 30 },
        { op: 'assert', assert: { kind: 'player_moved', min: 0.1 } },
        { op: 'mark' },
        { op: 'input', action: 'move_right', frames: 30 },
        { op: 'assert', assert: { kind: 'player_moved', min: 0.1 } },
      ],
    },
    {
      id: 'no-fall-through',
      title: 'The player stands on the level',
      covers: 'default: after 2 s the player is above the kill plane',
      steps: [
        ...inLevel,
        { op: 'wait', seconds: 2 },
        { op: 'assert', assert: { kind: 'state', field: 'playerY', op: 'gt', value: -12 } },
      ],
    },
    {
      id: 'interact-and-jump',
      title: 'interact and jump reach the player',
      covers: 'default: the interact action triggers the expected signal',
      steps: [
        ...inLevel,
        { op: 'wait', untilSignal: 'Player:interacted', pressAction: 'interact', seconds: 3 },
        { op: 'wait', untilSignal: 'Player:jumped', pressAction: 'jump', seconds: 3 },
      ],
    },
    {
      id: 'hud',
      title: 'The HUD is visible and not overlapping',
      covers: 'default: UI HUD visible, inside the viewport, no overlaps',
      steps: [
        ...inLevel,
        { op: 'assert', assert: { kind: 'node', group: 'hud', min: 1 } },
        { op: 'assert', assert: { kind: 'ui_ok' } },
        { op: 'screenshot', check: 'not_blank' },
      ],
    },
    {
      id: 'pause-resume',
      title: 'Pause and resume',
      covers: 'default: pause/resume',
      steps: [
        ...inLevel,
        { op: 'input', action: 'pause', frames: 2 },
        { op: 'await', assert: { kind: 'state', field: 'paused', op: 'eq', value: true }, timeout_s: 3 },
        { op: 'input', action: 'pause', frames: 2 },
        { op: 'await', assert: { kind: 'state', field: 'paused', op: 'eq', value: false }, timeout_s: 3 },
      ],
    },
    {
      id: 'lose',
      title: 'The lose condition is reachable',
      covers: `lose: ${spec.lose_conditions.join('; ')}`,
      steps: [...inLevel, { op: 'wait', untilSignal: '/root/GameState:lost', pressAction: 'qa_lose', seconds: 3 }],
    },
    {
      id: 'win',
      title: 'The win condition is reachable',
      covers: `win: ${spec.win_conditions.join('; ')}`,
      steps: [
        ...inLevel,
        { op: 'wait', untilSignal: '/root/GameState:won', pressAction: 'qa_win', seconds: 3 },
        {
          op: 'await',
          assert: { kind: 'state', field: 'currentScene', op: 'eq', value: 'res://scenes/win.tscn' },
          timeout_s: 5,
        },
      ],
    },
  ];
  if (level2)
    s.push({
      id: 'level-2',
      title: 'Scene transition to level 2',
      covers: 'default: scene transition to level 2',
      steps: [
        { op: 'scene-change', scene: level2 },
        { op: 'await', assert: { kind: 'state', field: 'currentScene', op: 'eq', value: level2 }, timeout_s: 10 },
        { op: 'await', assert: { kind: 'state', field: 'playerFound', op: 'eq', value: true }, timeout_s: 10 },
      ],
    });
  if (spec.save_system.required)
    s.push({
      id: 'save-load',
      title: 'Save/load round trip',
      covers: `save: ${spec.save_system.description ?? 'required'}`,
      steps: [
        ...inLevel,
        { op: 'wait', untilSignal: '/root/GameState:save_verified', pressAction: 'qa_save_roundtrip', seconds: 3 },
      ],
    });
  return s.map((x) => ScenarioSchema.parse(x));
}
