// SPDX-License-Identifier: Apache-2.0
//
// Audit event vocabulary. Every agent-facing action, policy decision, Developer Mode change and Claude
// integration event is recorded with one of these types in the append-only, hash-chained audit log
// (studio/core/src/audit/audit-log.ts). Payloads are redacted before they are written; secrets never appear.

export const AUDIT_EVENTS = [
  // policy + tools
  'tool_call_allowed',
  'tool_call_denied',
  'tool_call_completed',
  'tool_call_failed',
  'approval_requested',
  'approval_granted',
  'approval_rejected',
  'approval_withdrawn',
  'approval_expired',
  'policy_override_added',
  'untrusted_content_flagged',
  // developer mode
  'developer_mode_enabled',
  'developer_mode_disabled',
  'developer_capability_granted',
  // workers
  'worker_registered',
  'worker_trust_changed',
  'worker_quarantined',
  'worker_released_by_owner',
  // provenance
  'asset_provenance_recorded',
  'asset_license_blocked',
  // Claude integration (Execution Patch 1 §38)
  'claude_desktop_connected',
  'claude_desktop_disconnected',
  'claude_tool_call',
  'claude_approval_requested',
  'claude_approval_granted',
  'claude_approval_rejected',
  'claude_provider_call',
  'claude_provider_error',
  'claude_session_opened',
  'claude_health_test',
  // pipeline
  'game_spec_created',
  'pipeline_run_created',
  'pipeline_stage_completed',
  'pipeline_resumed',
  'build_completed',
  'build_job_submitted',
  // System Evolution (Execution Patch 2 §17, §20, §22, §28)
  'config_change_proposed',
  'config_changed',
  'config_rolled_back',
  'evolution_proposed',
  'evolution_planned',
  'evolution_sandbox_created',
  'evolution_tested',
  'evolution_review_requested',
  'evolution_approved',
  'evolution_rejected',
  'evolution_checkpoint_created',
  'evolution_deployed',
  'evolution_health_check',
  'evolution_verified',
  'evolution_rolled_back',
  'evolution_blocked',
  'extension_inspected',
  'extension_installed',
  'extension_enabled',
  'extension_disabled',
  'extension_updated',
  'extension_rolled_back',
  'workflow_registered',
  'workflow_activated',
  'workflow_pinned',
  'provider_registered',
  'update_checked',
  'update_installed',
  'update_rolled_back',
  'update_channel_changed',
  'migration_applied',
  'safe_mode_entered',
  'safe_mode_exited',
  'diagnostics_run',
  'repair_applied',
] as const;
export type AuditEventType = (typeof AUDIT_EVENTS)[number];
