// SPDX-License-Identifier: Apache-2.0
//
// Remote build worker protocol (EXECUTION_PROMPT Phase 11). One contract shared by Studio Core (the client) and
// `modulex-build-worker` (the service), so both sides validate the same shapes.
//
//   POST /v1/pair                      {code, studio}          → {worker_id, token}   (one-time code, single use)
//   GET  /v1/health                                            → heartbeat            (bearer)
//   GET  /v1/capabilities                                      → BuildWorkerCapabilities (bearer)
//   POST /v1/jobs                      BuildJobSpec            → BuildJobView  (idempotent by job_id)
//   PUT  /v1/jobs/:id/bundle           raw git bundle bytes    → BuildJobView  (sha256 must match the spec)
//   GET  /v1/jobs/:id                                          → BuildJobView
//   POST /v1/jobs/:id/cancel                                   → BuildJobView
//   GET  /v1/jobs/:id/artifacts/:name                          → bytes (sha256 in the view)
//
// Rules: signing certificates, provisioning profiles and App Store Connect keys NEVER leave the worker; the Studio
// names a signing profile (`signing_profile`) and the worker resolves it locally. Capabilities list identities by
// NAME only. A job_id maps to exactly one job: re-POSTing the same spec returns the existing job, a different spec
// under the same id is refused (409).
import { z } from 'zod';

/** `bj_` + 26 lowercase Crockford base32 characters (ULID-like), generated by the Studio. */
export const BUILD_JOB_ID = /^bj_[0-9a-hjkmnp-tv-z]{26}$/;

export function isValidBuildJobId(id: string): boolean {
  return BUILD_JOB_ID.test(id);
}

const CROCKFORD = '0123456789abcdefghjkmnpqrstvwxyz';

/** A fresh build job id: 48-bit time prefix + 80 random bits, Crockford base32. */
export function newBuildJobId(now: number = Date.now(), random: (n: number) => Uint8Array = defaultRandom): string {
  let time = '';
  let t = Math.floor(now);
  for (let i = 0; i < 10; i++) {
    time = CROCKFORD[t % 32]! + time;
    t = Math.floor(t / 32);
  }
  const bytes = random(16);
  let rest = '';
  for (let i = 0; i < 16; i++) rest += CROCKFORD[bytes[i]! % 32]!;
  return `bj_${time}${rest}`;
}

function defaultRandom(n: number): Uint8Array {
  const b = new Uint8Array(n);
  globalThis.crypto.getRandomValues(b);
  return b;
}

export const BuildWorkerPlatform = z.enum(['ios', 'windows', 'android', 'macos']);
export type BuildWorkerPlatform = z.infer<typeof BuildWorkerPlatform>;

export const BuildJobSpec = z
  .object({
    job_id: z.string().regex(BUILD_JOB_ID),
    project_id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,63}$/),
    platform: BuildWorkerPlatform,
    profile: z.enum(['DEV', 'QA', 'PREVIEW', 'RELEASE']),
    /** Exact Godot version the project is pinned to (compat.json); the worker refuses a mismatch. */
    godot_version: z.string().regex(/^\d+\.\d+(\.\d+)?$/),
    preset: z.string().min(1).max(64),
    version: z.string().regex(/^\d+\.\d+\.\d+$/),
    assembly: z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/),
    /** The project snapshot (git bundle) the Studio uploads with PUT /bundle. */
    bundle: z.object({ sha256: z.string().regex(/^[0-9a-f]{64}$/), size: z.number().int().positive() }).strict(),
    /** A signing profile NAME configured on the worker (never key material). Null = unsigned export. */
    signing_profile: z
      .string()
      .regex(/^[A-Za-z0-9._-]{1,64}$/)
      .nullable(),
  })
  .strict();
export type BuildJobSpec = z.infer<typeof BuildJobSpec>;

export const BUILD_JOB_STATES = ['awaiting_bundle', 'queued', 'running', 'succeeded', 'failed', 'cancelled'] as const;
export type BuildJobState = (typeof BUILD_JOB_STATES)[number];
export const TERMINAL_BUILD_JOB_STATES: ReadonlySet<BuildJobState> = new Set(['succeeded', 'failed', 'cancelled']);

export const BUILD_JOB_FAILURES = [
  'godot_version_mismatch',
  'bundle_invalid',
  'export_failed',
  'signing_failed',
  'signing_profile_missing',
  'worker_restarted',
  'timeout',
] as const;
export type BuildJobFailure = (typeof BUILD_JOB_FAILURES)[number];

export interface BuildJobArtifact {
  name: string;
  size: number;
  sha256: string;
}

export interface BuildJobView {
  job_id: string;
  state: BuildJobState;
  /** True when the worker produced a signed artifact (iOS: a signed .ipa from xcodebuild -exportArchive). */
  signed: boolean;
  failure: BuildJobFailure | null;
  message: string | null;
  artifacts: BuildJobArtifact[];
  /** The last lines of the job log (already free of secrets: the worker never logs signing material). */
  log_tail: string[];
  created_at: string;
  updated_at: string;
  /** Wall-clock seconds the job ran (the Studio's cost ledger records worker minutes from this). */
  run_seconds: number;
}

export interface BuildWorkerCapabilities {
  worker_id: string;
  worker_version: string;
  os: string;
  platforms: BuildWorkerPlatform[];
  godot_version: string | null;
  xcode_version: string | null;
  /** Signing profile and identity NAMES only. */
  signing_profiles: string[];
  max_concurrent_jobs: number;
}

export const PairRequest = z
  .object({
    code: z.string().regex(/^[0-9A-Z]{4}-[0-9A-Z]{4}$/),
    studio: z.string().min(1).max(64),
  })
  .strict();
export type PairRequest = z.infer<typeof PairRequest>;

/** A worker URL the Studio may talk to: HTTPS, or plain HTTP to loopback only (tests, a same-host worker). */
export function isAllowedWorkerUrl(url: string): boolean {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  if (u.username || u.password) return false;
  if (u.protocol === 'https:') return true;
  return u.protocol === 'http:' && ['127.0.0.1', 'localhost', '[::1]'].includes(u.hostname);
}
