// SPDX-License-Identifier: Apache-2.0
//
// Asset state machine (Phase 8): Reference → Conditioning → Mesh → Texture → Material → Cleanup → UV → Rig →
// Animation → Collision → Optimisation → GLB. Every stage is done | skipped (not required) | blocked (no
// capability) | failed, with a reason. A character that needs a rig and has no rig capability ends BLOCKED
// "requires rigging" — a static mesh is never labelled a playable character.
import type { AssetCategory } from './validate.js';
import type { ProcessStep } from './process.js';

export const ASSET_STAGES = [
  'reference',
  'conditioning',
  'mesh',
  'texture',
  'material',
  'cleanup',
  'uv',
  'rig',
  'animation',
  'collision',
  'optimisation',
  'glb',
] as const;
export type AssetStage = (typeof ASSET_STAGES)[number];

export interface StageRow {
  stage: AssetStage;
  status: 'done' | 'skipped' | 'blocked' | 'failed';
  reason: string;
}

export interface AssetPlanInput {
  category: AssetCategory;
  /** What the generating workflow really produces (WorkflowDefinition.produces). */
  produces: readonly string[];
  needsRig: boolean;
  needsAnimation?: boolean;
  /** A rig / animation capability exists (a workflow tagged rig/ANIMATION, or an external adapter). */
  rigCapability?: boolean;
  animationCapability?: boolean;
  referenceProvided: boolean;
  processing: ProcessStep[] | null;
  validated: boolean | null;
}

export function assetStages(i: AssetPlanInput): {
  rows: StageRow[];
  status: 'SUCCESS' | 'BLOCKED' | 'FAILED';
  reason: string | null;
} {
  const has = (x: string) => i.produces.includes(x);
  const step = (name: string) => i.processing?.find((p) => p.step === name);
  const rows: StageRow[] = [
    {
      stage: 'reference',
      status: i.referenceProvided ? 'done' : 'skipped',
      reason: i.referenceProvided ? 'reference image supplied' : 'text-only workflow',
    },
    { stage: 'conditioning', status: 'skipped', reason: 'single-view conditioning inside the workflow' },
    {
      stage: 'mesh',
      status: has('mesh') ? 'done' : 'failed',
      reason: has('mesh') ? 'generated by the workflow' : 'the workflow produces no mesh',
    },
    {
      stage: 'texture',
      status: has('texture') ? 'done' : 'skipped',
      reason: has('texture') ? 'generated' : 'untextured mesh (the workflow does not texture)',
    },
    {
      stage: 'material',
      status: has('material') ? 'done' : 'skipped',
      reason: has('material') ? 'generated' : 'default material in Godot',
    },
    {
      stage: 'cleanup',
      status: step('cleanup') ? 'done' : i.processing ? 'skipped' : 'failed',
      reason: step('cleanup')?.detail ?? 'not processed',
    },
    { stage: 'uv', status: 'skipped', reason: 'no UV unwrap adapter configured (needed only for texturing)' },
  ];
  if (i.needsRig)
    rows.push(
      i.rigCapability
        ? { stage: 'rig', status: 'done', reason: 'rigged' }
        : { stage: 'rig', status: 'blocked', reason: 'requires rigging: no rig workflow or adapter is available' },
    );
  else rows.push({ stage: 'rig', status: 'skipped', reason: 'not required' });
  if (i.needsAnimation)
    rows.push(
      i.animationCapability
        ? { stage: 'animation', status: 'done', reason: 'animated' }
        : {
            stage: 'animation',
            status: 'blocked',
            reason: 'requires animation: no animation workflow or adapter is available',
          },
    );
  else rows.push({ stage: 'animation', status: 'skipped', reason: 'not required' });
  rows.push({
    stage: 'collision',
    status: 'skipped',
    reason: 'a primitive CollisionShape3D is fitted at placement time',
  });
  const opt = step('optimisation');
  rows.push({
    stage: 'optimisation',
    status: opt ? (opt.status === 'done' ? 'done' : 'skipped') : 'skipped',
    reason: opt?.detail ?? 'not processed',
  });
  rows.push({
    stage: 'glb',
    status: i.validated === true ? 'done' : i.validated === false ? 'failed' : 'skipped',
    reason: i.validated === true ? 'validated GLB' : i.validated === false ? 'validation failed' : 'not validated yet',
  });
  const failed = rows.find((r) => r.status === 'failed');
  const blocked = rows.find((r) => r.status === 'blocked');
  return {
    rows,
    status: failed ? 'FAILED' : blocked ? 'BLOCKED' : 'SUCCESS',
    reason: failed ? `${failed.stage}: ${failed.reason}` : blocked ? blocked.reason : null,
  };
}
