// SPDX-License-Identifier: Apache-2.0
//
// Game generator (Phases 6 + 10): compiles a validated GAME_SPEC into a complete, playable Godot 4.5.1 (.NET)
// project — the `game-3d-basic` template instantiated for this spec. Deterministic: the same spec always yields
// the same files, so a resumed run can compare instead of redo.
//
// What it produces (all plain text Godot resources; Godot re-saves them on import):
//   project.godot       name, main scene, input map from spec.controls (+ required defaults), GameState and
//                       ModulexQa autoloads, both editor plugins, file logging for debug builds
//   <Assembly>.csproj   Godot.NET.Sdk/4.5.1, the pinned NuGet refs, the catalog EmbeddedResource, and the
//                       ExportRelease exclusion of both addons (build-profiles.md)
//   export_presets.cfg  "Windows Desktop", "Android" (arm64, APK), "iOS" (team id empty → PREPARED only)
//   scripts/*.gd        game_state (score, lives, levels, save), player, collectible, hazard, exit, level,
//                       hud (pause), main_menu, shop, win
//   scenes/*.tscn       one scene per spec level (ground, light, player, collectibles, hazards, exit, HUD),
//                       plus main menu / shop when the spec lists them, and a win screen
//
// Assets are PROCEDURAL primitives (capsule player, glowing collectibles, hazard spheres, exit pad). They are
// recorded with provenance `source: procedural`; AI-generated assets replace them in Phase 7/8 when a TRUSTED
// ComfyUI worker exists. Nothing here claims an asset was AI-generated.
import { RELEASE_EXCLUSION_CSPROJ, type GameSpec } from '@modulex/shared';

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedProject {
  assembly: string;
  slug: string;
  mainScene: string;
  levelScenes: string[];
  files: GeneratedFile[];
  /** Procedural placeholder assets, by spec asset id → the scene that defines them. */
  proceduralAssets: Record<string, string>;
}

const NUGET = [
  ['com.IvanMurzak.ReflectorNet', '5.4.1'],
  ['com.IvanMurzak.McpPlugin', '8.6.0'],
] as const;

/** `space-kid-journey` → `SpaceKidJourney` (a valid C# assembly / namespace identifier). */
export function assemblyName(id: string): string {
  const s = id
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join('');
  return /^[A-Za-z]/.test(s) ? s : `Game${s}`;
}

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

// Godot physical keycodes (Key enum) for the names the spec uses.
const SPECIAL: Record<string, number> = {
  up: 4194320,
  down: 4194322,
  left: 4194319,
  right: 4194321,
  space: 32,
  escape: 4194305,
  esc: 4194305,
  enter: 4194309,
  return: 4194309,
  tab: 4194306,
  shift: 4194325,
  ctrl: 4194326,
  control: 4194326,
  alt: 4194328,
  backspace: 4194308,
};

export function physicalKeycode(name: string): number | null {
  const k = name.trim().toLowerCase();
  if (k in SPECIAL) return SPECIAL[k]!;
  if (/^[a-z]$/.test(k)) return k.toUpperCase().charCodeAt(0);
  if (/^[0-9]$/.test(k)) return k.charCodeAt(0);
  if (/^f([1-9]|1[0-2])$/.test(k)) return 4194332 + Number(k.slice(1)) - 1;
  return null;
}

const keyEvent = (code: number) =>
  `Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":${code},"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)`;

/** Actions the generated gameplay needs even if the spec omits them. */
const REQUIRED_ACTIONS: Record<string, string[]> = {
  move_forward: ['W', 'Up'],
  move_back: ['S', 'Down'],
  move_left: ['A', 'Left'],
  move_right: ['D', 'Right'],
  jump: ['Space'],
  interact: ['E'],
  pause: ['Escape'],
};

function inputMap(spec: GameSpec): string {
  const actions = new Map<string, string[]>();
  for (const [a, keys] of Object.entries(REQUIRED_ACTIONS)) actions.set(a, keys);
  for (const c of spec.controls) if (c.default_keys.length) actions.set(c.action, c.default_keys);
  const out: string[] = [];
  for (const [action, keys] of [...actions.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const codes = [...new Set(keys.map(physicalKeycode).filter((c): c is number => c !== null))];
    out.push(`${action}={\n"deadzone": 0.2,\n"events": [${codes.map(keyEvent).join(', ')}]\n}`);
  }
  return out.join('\n');
}

// ------------------------------------------------------------------ GDScript

const GAME_STATE = (spec: GameSpec, levels: string[], shop: string | null, menu: string | null) => `extends Node
## Global game state (autoload "GameState"). Generated by ModuleX Game Studio from the Game Specification.

signal score_changed(score: int)
signal lives_changed(lives: int)
signal message(text: String)

const LEVELS: Array[String] = [${levels.map((l) => `"${l}"`).join(', ')}]
const LEVEL_NAMES: Array[String] = [${spec.levels.map((l) => `"${esc(l.name)}"`).join(', ')}]
const LEVEL_GOALS: Array[String] = [${spec.levels.map((l) => `"${esc(l.goal)}"`).join(', ')}]
const SHOP_SCENE := "${shop ?? ''}"
const MENU_SCENE := "${menu ?? ''}"
const WIN_SCENE := "res://scenes/win.tscn"
const SAVE_ENABLED := ${spec.save_system.required ? 'true' : 'false'}
const SAVE_PATH := "user://save.json"
const START_LIVES := 3

var score := 0
var lives := START_LIVES
var level_index := 0
var unlocked := 1
var cosmetics: Dictionary = {}


func _ready() -> void:
	load_game()


func start_game() -> void:
	score = 0
	lives = START_LIVES
	level_index = 0
	_go_level()


func continue_game() -> void:
	level_index = clampi(unlocked - 1, 0, LEVELS.size() - 1)
	lives = START_LIVES
	_go_level()


func level_name() -> String:
	return LEVEL_NAMES[level_index] if level_index < LEVEL_NAMES.size() else ""


func level_goal() -> String:
	return LEVEL_GOALS[level_index] if level_index < LEVEL_GOALS.size() else ""


func add_score(points: int) -> void:
	score += points
	score_changed.emit(score)


func hit() -> void:
	lives -= 1
	lives_changed.emit(lives)
	if lives <= 0:
		lose()


func level_complete() -> void:
	level_index += 1
	unlocked = maxi(unlocked, level_index + 1)
	save_game()
	if level_index >= LEVELS.size():
		get_tree().call_deferred("change_scene_to_file", WIN_SCENE)
	elif SHOP_SCENE != "":
		get_tree().call_deferred("change_scene_to_file", SHOP_SCENE)
	else:
		_go_level()


func continue_from_shop() -> void:
	_go_level()


func lose() -> void:
	message.emit("Try again!")
	lives = START_LIVES
	_go_level()


func back_to_menu() -> void:
	if MENU_SCENE != "":
		get_tree().call_deferred("change_scene_to_file", MENU_SCENE)
	else:
		start_game()


func buy(item: String, cost: int) -> bool:
	if score < cost or cosmetics.has(item):
		return false
	score -= cost
	cosmetics[item] = true
	score_changed.emit(score)
	save_game()
	return true


func _go_level() -> void:
	get_tree().paused = false
	get_tree().call_deferred("change_scene_to_file", LEVELS[level_index])


func save_game() -> void:
	if not SAVE_ENABLED:
		return
	var f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify({"score": score, "unlocked": unlocked, "cosmetics": cosmetics}))


func load_game() -> void:
	if not SAVE_ENABLED or not FileAccess.file_exists(SAVE_PATH):
		return
	var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if f == null:
		return
	var data = JSON.parse_string(f.get_as_text())
	if data is Dictionary:
		score = int(data.get("score", 0))
		unlocked = int(data.get("unlocked", 1))
		cosmetics = data.get("cosmetics", {})
`;

const PLAYER = `extends CharacterBody3D
## Third-person player controller. Moves with move_forward/back/left/right, jumps with jump.

const SPEED := 6.0
const JUMP_VELOCITY := 5.5
const KILL_PLANE := -12.0

var gravity: float = ProjectSettings.get_setting("physics/3d/default_gravity")
var _knockback := Vector3.ZERO


func _ready() -> void:
	add_to_group("player")
	if GameState.cosmetics.has("suit_gold"):
		_tint(Color(1.0, 0.8, 0.2))
	elif GameState.cosmetics.has("suit_blue"):
		_tint(Color(0.3, 0.5, 1.0))


func _tint(c: Color) -> void:
	var mesh := get_node_or_null("Mesh") as MeshInstance3D
	if mesh:
		var m := StandardMaterial3D.new()
		m.albedo_color = c
		mesh.material_override = m


func _physics_process(delta: float) -> void:
	if not is_on_floor():
		velocity.y -= gravity * delta
	if Input.is_action_just_pressed("jump") and is_on_floor():
		velocity.y = JUMP_VELOCITY
	var input := Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	var dir := Vector3(input.x, 0.0, input.y)
	if dir.length() > 0.01:
		dir = dir.normalized()
		velocity.x = dir.x * SPEED
		velocity.z = dir.z * SPEED
		look_at(global_position + Vector3(dir.x, 0.0, dir.z), Vector3.UP)
	else:
		velocity.x = move_toward(velocity.x, 0.0, SPEED)
		velocity.z = move_toward(velocity.z, 0.0, SPEED)
	velocity += _knockback
	_knockback = _knockback.move_toward(Vector3.ZERO, 20.0 * delta)
	move_and_slide()
	if global_position.y < KILL_PLANE:
		GameState.lose()


func knockback(from: Vector3) -> void:
	var away := (global_position - from)
	away.y = 0.0
	_knockback = away.normalized() * 8.0 + Vector3.UP * 3.0
`;

const COLLECTIBLE = `extends Area3D
## A collectible: +value points, then disappears. Counts toward the level goal.

@export var value := 1


func _ready() -> void:
	add_to_group("collectible")
	body_entered.connect(_on_body_entered)


func _process(delta: float) -> void:
	rotate_y(2.0 * delta)


func _on_body_entered(body: Node) -> void:
	if body.is_in_group("player"):
		GameState.add_score(value)
		get_tree().call_group("level", "on_collected", self)
		queue_free()
`;

const HAZARD = `extends Area3D
## A moving hazard: touching it costs a life and knocks the player back.

@export var amplitude := 3.0
@export var speed := 1.2
var _origin := Vector3.ZERO
var _t := 0.0


func _ready() -> void:
	_origin = position
	body_entered.connect(_on_body_entered)


func _process(delta: float) -> void:
	_t += delta * speed
	position = _origin + Vector3(sin(_t) * amplitude, 0.0, 0.0)


func _on_body_entered(body: Node) -> void:
	if body.is_in_group("player"):
		GameState.hit()
		if body.has_method("knockback"):
			body.knockback(global_position)
`;

const EXIT = `extends Area3D
## The level exit. Opens when every collectible is taken.

var open := false


func _ready() -> void:
	add_to_group("exit")
	body_entered.connect(_on_body_entered)
	_set_open(false)


func _set_open(value: bool) -> void:
	open = value
	var mesh := get_node_or_null("Mesh") as MeshInstance3D
	if mesh:
		mesh.transparency = 0.0 if open else 0.7


func set_open(value: bool) -> void:
	_set_open(value)


func _on_body_entered(body: Node) -> void:
	if open and body.is_in_group("player"):
		GameState.level_complete()
`;

const LEVEL = `extends Node3D
## Level controller: tracks remaining collectibles and opens the exit when they are all collected.

var remaining := 0


func _ready() -> void:
	add_to_group("level")
	remaining = get_tree().get_nodes_in_group("collectible").size()
	_update()


func on_collected(_item: Node) -> void:
	remaining -= 1
	_update()


func _update() -> void:
	get_tree().call_group("hud", "set_remaining", remaining)
	if remaining <= 0:
		get_tree().call_group("exit", "set_open", true)
`;

const HUD = `extends CanvasLayer
## HUD: score, lives, level name and goal, remaining collectibles, messages, and pause.

@onready var score_label: Label = $Panel/Score
@onready var lives_label: Label = $Panel/Lives
@onready var level_label: Label = $Panel/Level
@onready var goal_label: Label = $Panel/Goal
@onready var message_label: Label = $Message
@onready var pause_label: Label = $Paused


func _ready() -> void:
	add_to_group("hud")
	process_mode = Node.PROCESS_MODE_ALWAYS
	GameState.score_changed.connect(_on_score)
	GameState.lives_changed.connect(_on_lives)
	GameState.message.connect(_on_message)
	_on_score(GameState.score)
	_on_lives(GameState.lives)
	level_label.text = GameState.level_name()
	goal_label.text = GameState.level_goal()
	message_label.text = ""
	pause_label.visible = false


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("pause"):
		get_tree().paused = not get_tree().paused
		pause_label.visible = get_tree().paused


func set_remaining(n: int) -> void:
	message_label.text = "Exit open!" if n <= 0 else "Left: %d" % n


func _on_score(s: int) -> void:
	score_label.text = "Score: %d" % s


func _on_lives(l: int) -> void:
	lives_label.text = "Lives: %d" % l


func _on_message(t: String) -> void:
	message_label.text = t
`;

const MENU = `extends Control
## Main menu.


func _ready() -> void:
	$Box/Start.pressed.connect(GameState.start_game)
	$Box/Continue.visible = GameState.unlocked > 1
	$Box/Continue.pressed.connect(GameState.continue_game)
	$Box/Quit.pressed.connect(func() -> void: get_tree().quit())
	$Box/Start.grab_focus()
`;

const SHOP = `extends Control
## Shop between levels: spend score on cosmetic suits.

const ITEMS := {"suit_blue": 5, "suit_gold": 15}


func _ready() -> void:
	$Box/Blue.pressed.connect(_buy.bind("suit_blue"))
	$Box/Gold.pressed.connect(_buy.bind("suit_gold"))
	$Box/Continue.pressed.connect(GameState.continue_from_shop)
	_refresh()
	$Box/Continue.grab_focus()


func _buy(item: String) -> void:
	GameState.buy(item, ITEMS[item])
	_refresh()


func _refresh() -> void:
	$Box/Score.text = "Score: %d" % GameState.score
	$Box/Blue.disabled = GameState.cosmetics.has("suit_blue") or GameState.score < ITEMS["suit_blue"]
	$Box/Gold.disabled = GameState.cosmetics.has("suit_gold") or GameState.score < ITEMS["suit_gold"]
`;

const WIN = `extends Control
## Win screen.


func _ready() -> void:
	$Box/Score.text = "Score: %d" % GameState.score
	$Box/Again.pressed.connect(GameState.back_to_menu)
	$Box/Again.grab_focus()
`;

// ------------------------------------------------------------------ scenes

const PLAYER_TSCN = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/player.gd" id="1_script"]

[sub_resource type="CapsuleShape3D" id="Shape_body"]

[sub_resource type="StandardMaterial3D" id="Mat_body"]
albedo_color = Color(0.95, 0.95, 0.97, 1)

[sub_resource type="CapsuleMesh" id="Mesh_body"]
material = SubResource("Mat_body")

[node name="Player" type="CharacterBody3D"]
script = ExtResource("1_script")

[node name="Collision" type="CollisionShape3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0)
shape = SubResource("Shape_body")

[node name="Mesh" type="MeshInstance3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0)
mesh = SubResource("Mesh_body")

[node name="Camera" type="Camera3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 0.906308, 0.422618, 0, -0.422618, 0.906308, 0, 4.5, 7)
current = true
`;

const COLLECTIBLE_TSCN = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/collectible.gd" id="1_script"]

[sub_resource type="SphereShape3D" id="Shape_pick"]
radius = 0.6

[sub_resource type="StandardMaterial3D" id="Mat_pick"]
albedo_color = Color(1, 0.84, 0.2, 1)
emission_enabled = true
emission = Color(1, 0.75, 0.1, 1)

[sub_resource type="PrismMesh" id="Mesh_pick"]
material = SubResource("Mat_pick")
size = Vector3(0.7, 0.7, 0.25)

[node name="Collectible" type="Area3D"]
script = ExtResource("1_script")

[node name="Collision" type="CollisionShape3D" parent="."]
shape = SubResource("Shape_pick")

[node name="Mesh" type="MeshInstance3D" parent="."]
mesh = SubResource("Mesh_pick")
`;

const HAZARD_TSCN = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/hazard.gd" id="1_script"]

[sub_resource type="SphereShape3D" id="Shape_hz"]
radius = 0.8

[sub_resource type="StandardMaterial3D" id="Mat_hz"]
albedo_color = Color(0.9, 0.28, 0.3, 1)

[sub_resource type="SphereMesh" id="Mesh_hz"]
material = SubResource("Mat_hz")
radius = 0.8
height = 1.6

[node name="Hazard" type="Area3D"]
script = ExtResource("1_script")

[node name="Collision" type="CollisionShape3D" parent="."]
shape = SubResource("Shape_hz")

[node name="Mesh" type="MeshInstance3D" parent="."]
mesh = SubResource("Mesh_hz")
`;

const EXIT_TSCN = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/exit.gd" id="1_script"]

[sub_resource type="CylinderShape3D" id="Shape_exit"]
radius = 1.2
height = 2.0

[sub_resource type="StandardMaterial3D" id="Mat_exit"]
albedo_color = Color(0.35, 0.85, 0.6, 1)
emission_enabled = true
emission = Color(0.2, 0.7, 0.45, 1)

[sub_resource type="CylinderMesh" id="Mesh_exit"]
material = SubResource("Mat_exit")
top_radius = 1.2
bottom_radius = 1.2
height = 0.2

[node name="Exit" type="Area3D"]
script = ExtResource("1_script")

[node name="Collision" type="CollisionShape3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0)
shape = SubResource("Shape_exit")

[node name="Mesh" type="MeshInstance3D" parent="."]
mesh = SubResource("Mesh_exit")
`;

const label = (name: string, top: number, text: string, size = 22) => `[node name="${name}" type="Label" parent="Panel"]
offset_left = 16.0
offset_top = ${top}.0
offset_right = 520.0
offset_bottom = ${top + 30}.0
theme_override_font_sizes/font_size = ${size}
text = "${esc(text)}"
`;

const HUD_TSCN = `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/hud.gd" id="1_script"]

[node name="HUD" type="CanvasLayer"]
script = ExtResource("1_script")

[node name="Panel" type="Control" parent="."]
layout_mode = 3
anchors_preset = 0
offset_right = 540.0
offset_bottom = 150.0
mouse_filter = 2

${label('Score', 10, 'Score: 0')}
${label('Lives', 40, 'Lives: 3')}
${label('Level', 70, '', 18)}
${label('Goal', 98, '', 16)}
[node name="Message" type="Label" parent="."]
anchors_preset = 5
anchor_left = 0.5
anchor_right = 0.5
offset_left = -260.0
offset_top = 16.0
offset_right = 260.0
offset_bottom = 52.0
horizontal_alignment = 1
theme_override_font_sizes/font_size = 24

[node name="Paused" type="Label" parent="."]
anchors_preset = 8
anchor_left = 0.5
anchor_top = 0.5
anchor_right = 0.5
anchor_bottom = 0.5
offset_left = -120.0
offset_top = -24.0
offset_right = 120.0
offset_bottom = 24.0
horizontal_alignment = 1
theme_override_font_sizes/font_size = 36
text = "Paused"
`;

function levelTscn(index: number, collectibles: number, hazards: number): string {
  const hue = [0.35, 0.55, 0.12, 0.75, 0.9][index % 5]!;
  const ground = `Color(${(0.3 + hue * 0.3).toFixed(2)}, ${(0.45 + (1 - hue) * 0.2).toFixed(2)}, ${(0.35 + hue * 0.25).toFixed(2)}, 1)`;
  const nodes: string[] = [];
  for (let i = 0; i < collectibles; i++) {
    const a = (i / collectibles) * Math.PI * 2;
    const r = 5 + (i % 3) * 3;
    nodes.push(`[node name="Collectible${i + 1}" parent="." instance=ExtResource("3_collectible")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, ${(Math.cos(a) * r).toFixed(2)}, 1, ${(Math.sin(a) * r).toFixed(2)})
`);
  }
  for (let i = 0; i < hazards; i++) {
    nodes.push(`[node name="Hazard${i + 1}" parent="." instance=ExtResource("4_hazard")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.8, ${(-6 - i * 4).toFixed(2)})
`);
  }
  return `[gd_scene load_steps=11 format=3]

[ext_resource type="Script" path="res://scripts/level.gd" id="1_level"]
[ext_resource type="PackedScene" path="res://scenes/player.tscn" id="2_player"]
[ext_resource type="PackedScene" path="res://scenes/collectible.tscn" id="3_collectible"]
[ext_resource type="PackedScene" path="res://scenes/hazard.tscn" id="4_hazard"]
[ext_resource type="PackedScene" path="res://scenes/exit.tscn" id="5_exit"]
[ext_resource type="PackedScene" path="res://scenes/hud.tscn" id="6_hud"]

[sub_resource type="BoxShape3D" id="Shape_ground"]
size = Vector3(40, 1, 40)

[sub_resource type="StandardMaterial3D" id="Mat_ground"]
albedo_color = ${ground}

[sub_resource type="BoxMesh" id="Mesh_ground"]
material = SubResource("Mat_ground")
size = Vector3(40, 1, 40)

[sub_resource type="Environment" id="Env"]
background_mode = 1
background_color = Color(0.08, 0.09, 0.12, 1)
ambient_light_source = 2
ambient_light_color = Color(0.6, 0.62, 0.7, 1)
ambient_light_energy = 0.6

[node name="Level" type="Node3D"]
script = ExtResource("1_level")

[node name="Environment" type="WorldEnvironment" parent="."]
environment = SubResource("Env")

[node name="Sun" type="DirectionalLight3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 0.707107, 0.707107, 0, -0.707107, 0.707107, 0, 10, 0)
shadow_enabled = true

[node name="Ground" type="StaticBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)

[node name="Collision" type="CollisionShape3D" parent="Ground"]
shape = SubResource("Shape_ground")

[node name="Mesh" type="MeshInstance3D" parent="Ground"]
mesh = SubResource("Mesh_ground")

[node name="Player" parent="." instance=ExtResource("2_player")]

${nodes.join('\n')}
[node name="Exit" parent="." instance=ExtResource("5_exit")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 14)

[node name="HUD" parent="." instance=ExtResource("6_hud")]
`;
}

const uiScene = (name: string, script: string, title: string, controls: string) => `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/${script}" id="1_script"]

[node name="${name}" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_script")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.07, 0.08, 0.1, 1)

[node name="Box" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 8
anchor_left = 0.5
anchor_top = 0.5
anchor_right = 0.5
anchor_bottom = 0.5
offset_left = -200.0
offset_top = -150.0
offset_right = 200.0
offset_bottom = 150.0
theme_override_constants/separation = 14

[node name="Title" type="Label" parent="Box"]
layout_mode = 2
theme_override_font_sizes/font_size = 36
horizontal_alignment = 1
text = "${esc(title)}"

${controls}`;

const button = (name: string, text: string) => `[node name="${name}" type="Button" parent="Box"]
custom_minimum_size = Vector2(0, 48)
layout_mode = 2
text = "${esc(text)}"
`;
const scoreLabel = `[node name="Score" type="Label" parent="Box"]
layout_mode = 2
horizontal_alignment = 1
text = "Score: 0"
`;

// ------------------------------------------------------------------ project files

function projectGodot(spec: GameSpec, assembly: string, main: string): string {
  return `; Engine configuration file.
; Generated by ModuleX Game Studio from the Game Specification of "${esc(spec.project.id)}".

config_version=5

[application]

config/name="${esc(spec.project.name)}"
config/description="${esc(spec.game_loop)}"
run/main_scene="${main}"
config/features=PackedStringArray("4.5", "C#")
config/version="0.1.0"

[autoload]

GameState="*res://scripts/game_state.gd"
ModulexQa="*res://addons/modulex_studio/Runtime/Qa/ModulexQaAutoload.cs"

[debug]

file_logging/enable_file_logging=true

[display]

window/size/viewport_width=1280
window/size/viewport_height=720

[dotnet]

project/assembly_name="${assembly}"

[editor_plugins]

enabled=PackedStringArray("res://addons/godot_mcp/plugin.cfg", "res://addons/modulex_studio/plugin.cfg")

[input]

${inputMap(spec)}

[rendering]

textures/vram_compression/import_etc2_astc=true
`;
}

function csproj(assembly: string): string {
  return `<Project Sdk="Godot.NET.Sdk/4.5.1">
  <!-- Generated by ModuleX Game Studio. The NuGet pins and the catalog embed are the Godot-MCP addon's
       consumer-install contract; the ExportRelease group strips the MCP/QA stack from PREVIEW/RELEASE builds. -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <RootNamespace>${assembly}</RootNamespace>
    <AssemblyName>${assembly}</AssemblyName>
  </PropertyGroup>

  <!-- The MCP stack's packages are referenced only outside ExportRelease: excluding the addon sources alone still
       copies McpPlugin/ReflectorNet/SignalR into a release export (found by the distributable check, D-042). -->
  <ItemGroup Condition="'$(Configuration)' != 'ExportRelease'">
${NUGET.map(([n, v]) => `    <PackageReference Include="${n}" Version="${v}" />`).join('\n')}
    <EmbeddedResource Include="addons/godot_mcp/extensions.catalog.json" LogicalName="Godot-MCP.extensions.catalog.json" />
  </ItemGroup>

  ${RELEASE_EXCLUSION_CSPROJ.replace(/\n/g, '\n  ')}
</Project>
`;
}

/** A Visual Studio solution with the one project — Godot's C# export requires it (D-002, D-011). */
export function solution(assembly: string, projectGuid: string): string {
  const csharp = 'FAE04EC0-301F-11D3-BF4B-00C04F79EFBC';
  return `Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
Project("{${csharp}}") = "${assembly}", "${assembly}.csproj", "{${projectGuid}}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		ExportDebug|Any CPU = ExportDebug|Any CPU
		ExportRelease|Any CPU = ExportRelease|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{${projectGuid}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{${projectGuid}}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{${projectGuid}}.ExportDebug|Any CPU.ActiveCfg = ExportDebug|Any CPU
		{${projectGuid}}.ExportDebug|Any CPU.Build.0 = ExportDebug|Any CPU
		{${projectGuid}}.ExportRelease|Any CPU.ActiveCfg = ExportRelease|Any CPU
		{${projectGuid}}.ExportRelease|Any CPU.Build.0 = ExportRelease|Any CPU
	EndGlobalSection
EndGlobal
`;
}

function exportPresets(spec: GameSpec, assembly: string): string {
  const slug = assembly.toLowerCase();
  const common = (i: number, name: string, platform: string, path: string) => `[preset.${i}]

name="${name}"
platform="${platform}"
runnable=true
advanced_options=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=".modulex/*, build/*, build-output/*"
export_path="${path}"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2
`;
  return `${common(0, 'Windows Desktop', 'Windows Desktop', `build/windows/${assembly}.exe`)}
[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_wrapper=1
binary_format/embed_pck=false
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
binary_format/architecture="x86_64"
codesign/enable=false
application/modify_resources=true
application/icon=""
application/file_version="0.1.0.0"
application/product_version="0.1.0.0"
application/company_name="ModuleX Game Studio"
application/product_name="${esc(spec.project.name)}"
application/file_description="${esc(spec.project.name)}"
application/copyright=""
application/trademarks=""
application/export_angle=0
application/export_d3d12=0
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=true
dotnet/embed_build_outputs=false

${common(1, 'Android', 'Android', `build/android/${assembly}.apk`)}
[preset.1.options]

custom_template/debug=""
custom_template/release=""
gradle_build/use_gradle_build=false
gradle_build/export_format=0
architectures/armeabi-v7a=false
architectures/arm64-v8a=true
architectures/x86=false
architectures/x86_64=false
version/code=1
version/name="0.1.0"
package/unique_name="com.modulex.${slug}"
package/name="${esc(spec.project.name)}"
package/signed=true
screen/immersive_mode=true
keystore/debug=""
keystore/debug_user=""
keystore/debug_password=""
keystore/release=""
keystore/release_user=""
keystore/release_password=""
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=true
dotnet/embed_build_outputs=false

${common(2, 'iOS', 'iOS', `build/ios/${assembly}.ipa`)}
[preset.2.options]

custom_template/debug=""
custom_template/release=""
application/app_store_team_id=""
application/bundle_identifier="com.modulex.${slug}"
application/short_version="0.1.0"
application/version="1"
application/min_ios_version="14.0"
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=true
dotnet/embed_build_outputs=false
`;
}

// ------------------------------------------------------------------ entry

export function generateProject(
  spec: GameSpec,
  projectGuid = '8F2C4E10-5B7A-4D3E-9A61-2C0D1E7F4A90',
): GeneratedProject {
  const assembly = assemblyName(spec.project.id);
  const sceneIds = new Set(spec.scenes.map((s) => s.id));
  const menuId = [...sceneIds].find((s) => /menu|title|start/i.test(s)) ?? null;
  const shopId = [...sceneIds].find((s) => /shop|store/i.test(s)) ?? null;
  const levelScenes = spec.levels.map((l) => `res://scenes/${l.scene}.tscn`);
  const menu = menuId ? `res://scenes/${menuId}.tscn` : null;
  const shop = shopId ? `res://scenes/${shopId}.tscn` : null;
  const mainScene = menu ?? levelScenes[0]!;
  const hazardous = spec.mechanics.some((m) =>
    /hazard|enemy|meteor|obstacle|trap|damage|خطر|عدو/i.test(`${m.id} ${m.description}`),
  );

  const files: GeneratedFile[] = [
    { path: 'project.godot', content: projectGodot(spec, assembly, mainScene) },
    { path: `${assembly}.csproj`, content: csproj(assembly) },
    { path: `${assembly}.sln`, content: solution(assembly, projectGuid) },
    { path: 'export_presets.cfg', content: exportPresets(spec, assembly) },
    { path: 'scripts/game_state.gd', content: GAME_STATE(spec, levelScenes, shop, menu) },
    { path: 'scripts/player.gd', content: PLAYER },
    { path: 'scripts/collectible.gd', content: COLLECTIBLE },
    { path: 'scripts/hazard.gd', content: HAZARD },
    { path: 'scripts/exit.gd', content: EXIT },
    { path: 'scripts/level.gd', content: LEVEL },
    { path: 'scripts/hud.gd', content: HUD },
    { path: 'scripts/win.gd', content: WIN },
    { path: 'scenes/player.tscn', content: PLAYER_TSCN },
    { path: 'scenes/collectible.tscn', content: COLLECTIBLE_TSCN },
    { path: 'scenes/hazard.tscn', content: HAZARD_TSCN },
    { path: 'scenes/exit.tscn', content: EXIT_TSCN },
    { path: 'scenes/hud.tscn', content: HUD_TSCN },
    {
      path: 'scenes/win.tscn',
      content: uiScene(
        'Win',
        'win.gd',
        spec.win_conditions[0] ?? 'You win!',
        `${scoreLabel}\n${button('Again', 'Play again')}`,
      ),
    },
  ];
  spec.levels.forEach((l, i) => {
    files.push({
      path: `scenes/${l.scene}.tscn`,
      content: levelTscn(i, 5 + i * 2, hazardous ? 1 + Math.min(i, 3) : 0),
    });
  });
  if (menuId) {
    files.push({ path: 'scripts/main_menu.gd', content: MENU });
    files.push({
      path: `scenes/${menuId}.tscn`,
      content: uiScene(
        'MainMenu',
        'main_menu.gd',
        spec.project.name,
        `${button('Start', 'Start')}\n${button('Continue', 'Continue')}\n${button('Quit', 'Quit')}`,
      ),
    });
  }
  if (shopId) {
    files.push({ path: 'scripts/shop.gd', content: SHOP });
    files.push({
      path: `scenes/${shopId}.tscn`,
      content: uiScene(
        'Shop',
        'shop.gd',
        'Shop',
        `${scoreLabel}\n${button('Blue', 'Blue suit — 5')}\n${button('Gold', 'Gold suit — 15')}\n${button('Continue', 'Continue')}`,
      ),
    });
  }
  // Scenes the spec lists that the template does not specialise get an honest placeholder screen.
  for (const s of spec.scenes) {
    if (spec.levels.some((l) => l.scene === s.id) || s.id === menuId || s.id === shopId) continue;
    files.push({
      path: `scenes/${s.id}.tscn`,
      content: uiScene(assemblyName(s.id), 'win.gd', s.purpose, `${scoreLabel}\n${button('Again', 'Back')}`),
    });
  }
  const proceduralAssets: Record<string, string> = {};
  for (const a of spec.assets) {
    proceduralAssets[a.id] =
      a.type === 'character'
        ? 'res://scenes/player.tscn'
        : a.type === 'environment'
          ? levelScenes[0]!
          : /hazard|meteor|enemy|obstacle/i.test(`${a.id} ${a.description}`)
            ? 'res://scenes/hazard.tscn'
            : /exit|rocket|portal|door|goal/i.test(`${a.id} ${a.description}`)
              ? 'res://scenes/exit.tscn'
              : 'res://scenes/collectible.tscn';
  }
  return { assembly, slug: assembly.toLowerCase(), mainScene, levelScenes, files, proceduralAssets };
}
